version: '3.8'

# Services
services:

  # Nginx Service
  nginx:
    image: nginx:1.19
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    restart: always
    depends_on:
      - php

  # PHP Service
  php:
    build: ./.docker/php
    working_dir: /var/www/php
    volumes:
      - ./src:/var/www/php
    restart: always
    depends_on:
      mysql:
        condition: service_healthy

  # MySQL Service
  mysql:
    image: hypriot/rpi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cuentas
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql
    restart: always
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - TZ=Europe/Madrid
      - SUBDOMAINS=pih0sue,pih0use
      - TOKEN=904c3e46-9b21-411e-8da4-606e6a701ba6
    restart: unless-stopped

  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=188.215.231.214 #optional
      - SERVERPORT=51820 #optional
      - PEERS=2 #optional
      - PEERDNS=1.1.1.1 #optional
      - ALLOWEDIPS=10.13.13.0/24,192.168.1.0/24
    volumes:
      - /home/pi/PH-prod/src/VPN/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
  
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: "host"
    volumes:
      - .docker/jellyfin/config:/config
      - .docker/jellyfin/cache:/cache
      - /media/pi/USB:/media
    restart: "unless-stopped"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000

  motioneye:
    container_name: motioneye
    image: ccrisan/motioneye:master-armhf
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/motioneye:/etc/motioneye
      - /var/lib/motioneye:/var/lib/motioneye
    ports:
      - 8765:8765
    devices:
      - /dev/video0:/dev/video0
  
volumes:
  mysqldata:
  plex_data:
  certs:
  html:
  vhostd:
  confd:

  